# Generated by Django 3.0.3 on 2020-06-11 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='amount',
            field=models.PositiveIntegerField(null=True, verbose_name='Balance'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Currency', verbose_name='Currency'),
        ),
    ]
