# Generated by Django 3.0.3 on 2020-06-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200611_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='usd_ratio',
            field=models.FloatField(default=1, verbose_name='USD ratio'),
        ),
    ]
